feat(i18n): add base Italian translations
strapi/strapi-plugin-seo pull request #13
Opened 2022-06-06 13:36 UTC by mithenks

This PR add Italian translations.

2022-06-13 13:57 UTC, Mcastres requested changes

2022-06-13 13:57 UTC, Mcastres commented on admin/src/components/CMEditView/RightLinksCompo/Summary/PreviewChecks/index.js
> +		  id: getTrad('SEOComponent.title.summary'),
You are not creating translations for `SEOComponent.title.summary` in en and fr but a `SEO Summary` one instead.

Can you please remove the `SEO Summary`, add the `SEOComponent.title.summary` in both fr and en?

2022-06-13 13:57 UTC, Mcastres commented on admin/src/components/CMEditView/RightLinksCompo/Summary/BrowserPreview/index.js
> +            id: getTrad('plugin.name'),
Can it be `Plugin.name`?

2022-06-13 13:57 UTC, Mcastres commented on admin/src/translations/en.json
> +  "SEO Summary": "SEO Summary"
Must be replaced. See comment above :)

2022-06-13 13:58 UTC, Mcastres commented
Thanks for your translation PR @mithenks 💪

2022-09-29 11:07 UTC, ecosse3 commented
Any idea when it will be merged? I want to provide Polish translations 😄

2023-10-22 00:16 UTC, SalahAdDin commented
@mithenks could you check this?

2024-12-19 13:40 UTC, closed without merging

2024-12-20 03:03 UTC, SalahAdDin commented
@mithenks  Why did you close it?